server:
  port: 8090
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #配置github
          uri: https://gitee.com/zhanggm1002/springcloud-demo-0325.git
          #配置搜索目录
          search-paths:
            - configfiles
      #配置分支
      label: test