server:
  port: 8090
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #配置github
          uri: https://github.com/wangke839/test.git
          #配置搜索目录
          search-paths:
            - configfiles
      #配置分支
      label: test